Repository ICE-STUDYRES/ice-studyroom, pull requests merged in 2025-02, with the labels that each got.

#125 [FE - #119, 122] 메인페이지 ui 수정 및 예약현황 순서 업데이트
  frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: fix

#126 [FE-#120] 예약자 QRCode 불러오기 및 출석 요청
  frontend/fr-study/src/pages/Mainpage/QRCodeFetcher.jsx
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: feature

#124 [BE-#31] QR 입실 구현
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/EncryptionService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/QRCodeService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/AESUtil.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/QRCodeUtil.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ReservationStatus.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/QrController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/QrEntranceRequest.java
  backend/src/main/java/com/ice/studyroom/global/exception/AttendanceException.java
  backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrRecognitionServiceTest.java
  backend/src/test/java/com/ice/studyroom/helper/ReservationTestHelper.java
Labels: feature

#130 [BE-#127 #128 #129] Penalty 도메인 분류 및 노쇼 확인 스케줄러 생성
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyRecordResponse.java
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/application/EmailVerificationService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/type/PenaltyReasonType.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/type/PenaltyStatus.java
  backend/src/main/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/type/PenaltyReasonType.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/type/PenaltyStatus.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/infrastructure/persistence/PenaltyRepository.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
  backend/src/main/java/com/ice/studyroom/global/dto/request/EmailRequest.java
  backend/src/main/java/com/ice/studyroom/global/service/EmailService.java
  backend/src/main/java/com/ice/studyroom/global/service/GmailService.java
  backend/src/test/java/com/ice/studyroom/domain/membership/infrastructure/email/EmailVerificationServiceTest.java
  backend/src/test/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateSchedulerTest.java
  backend/src/test/java/com/ice/studyroom/domain/penalty/application/PenaltyServiceTest.java
Labels: feature

#133 [FE - #116] 비밀번호 변경 기능 구현
  frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
  frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx
  frontend/fr-study/src/pages/Mainpage/ProfileDropdown.jsx
Labels: feature, ui

#135 [FE - #132] 최근 예약 불러오기 api 연동
  frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
Labels: feature

#140 [FE - #122] 내 예약 최신 순 나열
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: fix

#139 feat: 개인예약 생성 기능
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
Labels: feature, refactor

#143 [FE- #142] QR코드 스캔 및 출석요청 구현
  frontend/fr-study/src/pages/Mainpage/QRCodeFetcher.jsx
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: feature

#141 [BE-#134] 예약 취소 기능 구현
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/CancelReservationResponse.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrRecognitionServiceTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java
Labels: feature

#145 [BE-#136] 개인/단체 예약 패널티 여부 및 최근예약상태 조회
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ReservationStatus.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
Labels: refactor

#148 [BE-#136] 현재 시각 이전 스케줄에 대해서는 예약 불가 추가
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
Labels: refactor

#157 [BE-#151] 내 예약 조회 api 참여자 정보 반영
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetReservationsResponse.java
Labels: refactor

#161 [FE - #160] api 수정에 따른 코드 수정
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: refactor

#162 [FE - #123] 데이터 호출 수정
  frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: fix

#164 [FE - #137] 데이터 호출 및 취소 기능 구현
  frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
  frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx
Labels: feature, fix

#159 [BE - #150 #152 #158] 중복 예약 예외처리, admin 패널티 개선, BusinessException 통일
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/domain/entity/RoomTimeSlot.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminPenaltyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyControlResponse.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/Email.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateReservationRequest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java
Labels: fix

#165 [FE - #163] 연장하기 기능 구현
  frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx
Labels: feature

#167 [FE - #166] 단체, 개인예약 기능 업데이트
  frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
Labels: feature

#169 [BE - #168] 예약 취소 오류 수정
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/global/entity/BaseTimeEntity.java
Labels: bug

#173 [Fix] QR코드 출석체크 오류 수정
  frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: fix

#175 [FE - #] 전체예약조회 개인방 표기 오류 수정
  frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: fix

#181 [FE-#179] 잔여좌석 및 개인과 단체방 구별 UI&기능 구현
  frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
  frontend/fr-study/src/pages/Reservation/StudyRoomBookingUI.jsx
Labels: feature

#182 [FE - #176] 진행 중인 예약 없을 때 연장/취소 페이지 화면 수정
  frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx
Labels: fix

#183 [FE - #180] AccessToken 사용 함수 토큰 재발급 적용
  frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
  frontend/fr-study/src/pages/Mainpage/ProfileDropdown.jsx
  frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx
Labels: feature

#187 [BE-#171] 로그인 시 사용자 권한 반환
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/JwtToken.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberLoginRequest.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLoginResponse.java
Labels: feature

#186 [BE - # 184] 관리자 선점 생성/취소/목록 조회 dto 수정
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/infrastructure/persistence/RoomTimeSlotRepository.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminCreateOccupyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminOccupyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminCreateOccupyResponse.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminDeleteOccupyResponse.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminGetReservedResponse.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminOccupyResponse.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminRoomResponse.java
Labels: refactor

#189 [FE - #188] 메인페이지 ui 수정 및 하드코딩 제거
  frontend/fr-study/package.json
  frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
  frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx
Labels: feature, chore, ui

#195 [BE-#194] 유저 정보 조회 응답 데이터, 패널티 데이터 추가
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLookupResponse.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/test/java/com/ice/studyroom/domain/penalty/application/PenaltyServiceTest.java
Labels: feature

#193 [BE-#192] RT를 헤더를 통해서 전달하도록 수정
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/TokenRequest.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLoginResponse.java
Labels: refactor

#199 [FE-#198] Alert to Toast Message로 변경 후 구현
  frontend/fr-study/src/App.jsx
  frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx
  frontend/fr-study/src/pages/Mainpage/QRCodeFetcher.jsx
  frontend/fr-study/src/pages/Notification/Notification.jsx
  frontend/fr-study/src/pages/Notification/NotificationMessage.jsx
  frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
  frontend/fr-study/src/pages/Reservation/StudyRoomBookingUI.jsx
  frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: feature

#201 [FE-#196,197] 패널티 api 연결 및 내 예약 조회 방 상태 업데이트
  frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
  frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: feature

#202 [FE-#200] 예약 취소시 연장페이지에서 제거
  frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx
Labels: feature

#204 [FE-#203] Index file 세팅 변경으로 브라우저 이미지와 타이틀 변경
  frontend/fr-study/index.html
  frontend/fr-study/public/study.png
Labels: chore

#206 [FE-#205] 프로젝트 이중경로 문제 해결
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/postcss.config.cjs
  frontend/public/study.png
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/images/Alert.png
  frontend/src/assets/images/Calendar.png
  frontend/src/assets/images/Check.png
  frontend/src/assets/images/Edit.png
  frontend/src/assets/images/Log in.png
  frontend/src/assets/images/Log out.png
  frontend/src/assets/images/X.png
  frontend/src/assets/images/back.png
  frontend/src/assets/images/hufslogo.png
  frontend/src/assets/images/icon.png
  frontend/src/assets/images/iconx.png
  frontend/src/index.css
  frontend/src/main.css
  frontend/src/main.jsx
  frontend/src/pages/Mainpage/Mainpage.jsx
  frontend/src/pages/Mainpage/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/ProfileDropdown.jsx
  frontend/src/pages/Mainpage/QRCodeFetcher.jsx
  frontend/src/pages/Notification/Notification.jsx
  frontend/src/pages/Notification/NotificationMessage.jsx
  frontend/src/pages/Reservation/StudyRoomBookingHandler.jsx
  frontend/src/pages/Reservation/StudyRoomBookingUI.jsx
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
  frontend/tailwind.config.js
  frontend/vite.config.js
Labels: chore

#208 [FE-#207] 취소와 출석관련 메시지 로직 수정
  frontend/src/pages/Notification/NotificationMessage.jsx
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: fix

#210 [FE-#209] 프론트엔드 자동배포 설정 파일
  frontend/.github/workflows/deploy.yml
  frontend/vite.config.js
Labels: feature

#211 [FE-#211] 프론트엔드 자동배포 yml 키 값 수정본
  frontend/.github/workflows/deploy.yml
Labels: fix

#214 [BE-#213] server port, address 속성 추가
  backend/src/main/resources/application.properties
Labels: chore

#216 [BE-#215] CORS 설정 추가
  backend/src/main/java/com/ice/studyroom/config/CorsConfig.java
Labels: feature

#220 [FE-#219] 프론트엔드 파일 리팩토링
  frontend/src/pages/Mainpage/Mainpage.jsx
  frontend/src/pages/Mainpage/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/MemberHandlers.jsx
  frontend/src/pages/Mainpage/PenaltyHandlers.jsx
  frontend/src/pages/Mainpage/Popups.jsx
  frontend/src/pages/Mainpage/TokenHandler.jsx
  frontend/src/pages/Reservation/StudyRoomBookingHandler.jsx
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: refactor

#221 [FE-#219] 프론트엔드 폴더 구조 변경
  frontend/src/pages/Mainpage/Mainpage.jsx
  frontend/src/pages/Mainpage/components/Popups.jsx
  frontend/src/pages/Mainpage/components/ProfileDropdown.jsx
  frontend/src/pages/Mainpage/components/QRCodeFetcher.jsx
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
  frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
  frontend/src/pages/Mainpage/handlers/TokenHandler.jsx
  frontend/src/pages/Reservation/StudyRoomBookingHandler.jsx
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: refactor

#228 [FE-#227]예약 페이지 하드코딩제거
  frontend/src/App.jsx
  frontend/src/pages/Reservation/StudyRoomBookingHandler.jsx
  frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
  frontend/src/pages/Reservation/handlers/userInfomanager.jsx
Labels: feature

#229 [FE-#224] 로그아웃 기능 추가
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: feature

#226 hotfix: schedule entity dayOfWeekStatus 추가
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateScheduleRequest.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ScheduleResponse.java
Labels: fix

#231 [FE-#223] 토큰 저장 방식 변경
  frontend/src/pages/Mainpage/Mainpage.jsx
  frontend/src/pages/Mainpage/components/ProfileDropdown.jsx
  frontend/src/pages/Mainpage/components/QRCodeFetcher.jsx
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
  frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
  frontend/src/pages/Mainpage/handlers/TokenHandler.jsx
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
  frontend/src/pages/Reservation/handlers/userInfomanager.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: feature

#233 [BE-#232] 가입되지 않은 이메일로 로그인 시 예외처리
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
Labels: fix

#234 hotfix: schedule 스케줄러에 roomType 추가
  backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTask.java
Labels: fix

#235 [Hotfix] 참여자 정보 추가 오류 수정
  frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
Labels: fix

#237 [BE-#236] cd코드 실행 시 docker 한국 시간 설정
  .github/workflows/deploy-server.yml
Labels: fix

#239 [FE-#238] 회원가입 관련 기능 개선
  frontend/src/pages/Mainpage/Mainpage.jsx
  frontend/src/pages/Mainpage/components/Popups.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: feature

#240 [hotfix] cors http 메소드 추가
  backend/src/main/java/com/ice/studyroom/config/CorsConfig.java
Labels: fix

#242 [FE-#241] 비밀번호 변경 특수문자 추가
  frontend/src/pages/Mainpage/components/Popups.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: feature

#245 [BE-#244] 테스트 시나리오 1차 점검
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/QrController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/QrEntranceResponse.java
  backend/src/main/resources/application.properties
Labels: feature, fix

#248 [FE-#246] 참여자 추가 후 빈 배열 에러 해결
  frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
  frontend/src/pages/Reservation/handlers/userInfomanager.jsx
Labels: feature

#250 [hotfix] 비밀번호 규칙 무효화
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/UpdatePasswordRequest.java
Labels: fix

#252 [Fix-#251] 패널티 종료 일자, 스케줄러 버그 수정
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
Labels: fix

#253 [hotfix] spring 서버 시간 설정 추가
  backend/src/main/resources/application.properties
Labels: fix

#254 [FE-#243] 전체 예약 현황 페이지 수정
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: feature

#255 [hotfix] 패널티 스케줄러 오류 수정
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
Labels: fix

#257 [FE-#256] TimeSlot의 예약 가능한 시간 로직 변경
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
Labels: feature

#259 [FE-#258] 메인페이지 수정
  frontend/src/App.jsx
  frontend/src/pages/Mainpage/Mainpage.jsx
  frontend/src/pages/Mainpage/components/Popups.jsx
  frontend/src/pages/Mainpage/components/Signin.jsx
  frontend/src/pages/Mainpage/components/Signup.jsx
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: feature

#261 [FE-#260]하드코딩과 목업만 작성해놓은 어드민 페이지 구현
  frontend/src/App.jsx
  frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
  frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
  frontend/src/pages/Mainpage/Adminpage/PenaltyManagement.jsx
  frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx
Labels: feature

#264 [BE-#251] 패널티 부여, 해제 스케줄러 로직 수정
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/infrastructure/persistence/PenaltyRepository.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
Labels: refactor, fix

#266 [FE-#265] 페널티 ui 오류 수정
  frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
Labels: test

#267 [FE-#262] 연장 및 취소 페이지 예약자 오류 및 안내 문구 수정
  frontend/src/pages/Reservation/StudyRoomManage.jsx
Labels: test

#269 [hotfix] 노쇼 스케줄러 디버깅
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/test/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateSchedulerTest.java
Labels: bug

#270 [hotfix] docker 한국 시간 설정 추가
  backend/Dockerfile
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
Labels: bug

#271 [hotfix] 노쇼 스케줄러 버그 수정
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
Labels: bug

#273 [BE-#272] reservation 상태 변경 영속성 보장 개선
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrRecognitionServiceTest.java
Labels: refactor

#274 [hotfix] 테스트를 위한 스케줄러 시간 수정
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
Labels: fix

#277 [FE-#268] 약관 동의 기능 추가
  frontend/src/pages/Mainpage/components/Signup.jsx
  frontend/src/pages/Mainpage/components/TermsandPrivacy.jsx
Labels: feature

#279 [FE-#278] url명 변경
  frontend/src/App.jsx
  frontend/src/pages/Mainpage/components/Signin.jsx
  frontend/src/pages/Mainpage/components/Signup.jsx
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: fix

#276 [BE-#275] 패널티 인터셉터 제작
  backend/src/main/java/com/ice/studyroom/config/WebConfig.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/interceptor/PenaltyCheckInterceptor.java
Labels: feature

#286 [FE-#285] 스터디룸 선택시 시간 선택으로 변경 로직
  frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
Labels: feature

#288 [FE-#287] 로그아웃시 비로그인 메인페이지로 이동
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: test

#289 [BE-#284] 테스트 시나리오 점검
  backend/src/main/java/com/ice/studyroom/config/WebConfig.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
Labels: fix

#291 [FE-#290]예약 실패와 성공시 반환되는 메시지 로직 변경
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
  frontend/src/pages/ReservationStatus/AttendanceHandler.jsx
  frontend/src/pages/ReservationStatus/AttendanceSystem.jsx
Labels: feature

#293 [FE-#292] 토큰 재발급 테스트
  frontend/src/pages/Mainpage/Mainpage.jsx
  frontend/src/pages/Mainpage/components/ProfileDropdown.jsx
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
  frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
  frontend/src/pages/Mainpage/handlers/TokenHandler.jsx
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
Labels: test

#294 [FE-#292] 토큰 재발급 테스트
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
Labels: test

#297 [FE-#296] 전체 예약 조회 헤더 추가
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: fix

#302 [BE-#301] 예약 상태 업데이트 스케줄러 및 연장 예외처리
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ReservationStatus.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ReservationUpdateScheduler.java
Labels: feature

#303 [BE-#300] 개인예약의 경우 개인 정보만 반환
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetReservationsResponse.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ParticipantResponse.java
Labels: feature

#306 [FE-#305] 개인예약시 참여자 추가 버튼 제거 및 안내 UI 추가
  frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
Labels: feature

#309 [BE-#308] 개인, 단체 예약 정보 모두 반환하게 수정
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetReservationsResponse.java
Labels: fix

#313 [FE-#310] 내 예약 페이지 COMPLETED 상태 추가
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: fix

#314 [FE-#312] 연장 페이지 개인 예약 데이터 추가
  frontend/src/pages/Reservation/StudyRoomManage.jsx
Labels: fix

#316 [Fix] QR 스캐너 페이지 접근 방식 변경
  frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: fix

#318 [FE-#317] 패널티 적용된 회원 접근시 Toast Message 구현
  frontend/src/pages/Notification/NotificationMessage.jsx
Labels: feature

#319 [FE-#311] 페이지 이동 시 페널티 여부 검사
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: feature

#320 [hotfix] 인터셉터 예외 URL 오류 처리
  backend/src/main/java/com/ice/studyroom/config/WebConfig.java
Labels: bug

#321 [hotfix] cors 프론트도메인 설정
  backend/src/main/java/com/ice/studyroom/config/CorsConfig.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/AESUtil.java
Labels: fix

#323 [Fix-#322] cloud-front 응답 변경 우회를 위한 새로운 응답 정의
  backend/src/main/java/com/ice/studyroom/domain/penalty/interceptor/PenaltyCheckInterceptor.java
  backend/src/main/java/com/ice/studyroom/global/type/StatusCode.java
Labels: bug
