Repository ICE-STUDYRES/ice-studyroom, pull requests merged in 2025-03, with the labels that each got.

#327 [FE-#326] 로그아웃 api 호출 확인 후 정상 로그아웃
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: fix

#331 [FE-#330] 출석페이지 AT, RT 갱신 관련 수정
  frontend/src/pages/ReservationStatus/AttendanceHandler.jsx
Labels: fix

#336 [BE-#335] api 엔드포인트 인증 및 권환 분류
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java
Labels: feature

#339 [FE-#334] 비밀번호 변경, 로그아웃 토큰 만료시 재발급
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
  frontend/src/pages/Mainpage/handlers/TokenHandler.jsx
Labels: test

#338 [BE-#337] api 엔드포인트 인증 및 권한 수정
  backend/src/main/java/com/ice/studyroom/config/CorsConfig.java
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/TokenService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/QrController.java
Labels: fix

#342 [FE-#341] 토큰 재발급 함수 catch문으로 이동
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
Labels: fix

#344 [FE-#343] Attendant 로그인 설정
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: feature

#345 [FE-#343] Admin 로그인 훅 분리
  frontend/src/pages/Mainpage/components/AdminSignin.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: fix

#347 [BE-#346] token refresh 시, 기존 권한이 반영되지 않는 오류 수정
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/TokenService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtAuthenticationFilter.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
Labels: fix

#348 [FE-#340] 전체 예약현황 페이지, 연장 및 취소 기능 토큰 재발급 기능 추가
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: test

#351 [FE-#349] 입실하지 않았는데 연장 버튼이 클릭되는 오류 수정
  frontend/src/pages/Reservation/StudyRoomManage.jsx
Labels: fix

#355 [FE-#354] 토큰 재발급 호출 경로 수정
  frontend/src/pages/Mainpage/components/QRCodeFetcher.jsx
Labels: fix

#353 [BE-#352] 예약 연장 처리 로직 개선
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ReservationUpdateScheduler.java
Labels: refactor

#357 [FE-#356] 연장 기능 오류 해결 및 토큰 재발급 수정
  frontend/src/pages/Reservation/StudyRoomManage.jsx
Labels: test

#358 [FE-#342] 콘솔문구, 미사용 코드 제거
  frontend/src/pages/Mainpage/components/Popups.jsx
  frontend/src/pages/Mainpage/components/ProfileDropdown.jsx
  frontend/src/pages/Mainpage/components/Signin.jsx
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
  frontend/src/pages/Mainpage/handlers/TokenHandler.jsx
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/ReservationStatus/AttendanceHandler.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: refactor

#360 [FE-#359] AT 없을 때 api 호출하지 않도록 수정
  frontend/src/pages/Mainpage/Mainpage.jsx
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
  frontend/src/pages/Mainpage/handlers/TokenHandler.jsx
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: fix

#362 [Refactor] 서버 자동 배포 코드 개선
  .github/workflows/deploy-server.yml
  backend/Dockerfile
Labels: refactor

#364 [BE-#363] 예약 완료 안내 이메일 발송 기능
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/global/dto/request/EmailRequest.java
  backend/src/main/java/com/ice/studyroom/global/service/GmailService.java
  frontend/src/pages/Mainpage/components/Popups.jsx
Labels: feature

#366 [BE-365] 예약 스케줄 INSERT 쿼리문 수정
  backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTask.java
  backend/src/main/resources/application.properties
Labels: fix

#368 [BE-#367] 이메일 발송 기능 비동기 처리
  backend/src/main/java/com/ice/studyroom/config/AsyncConfig.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/global/service/EmailService.java
Labels: feature

#375 [FE-#374] 페널티 종료 일자 오류 수정
  frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
Labels: fix

#376 [Chore-#373] redis 비밀번호 설정을 통안 보안 강화
  backend/src/main/java/com/ice/studyroom/config/RedisConfig.java
  backend/src/main/resources/application.properties
Labels: chore

#377 [FE-#350]
  frontend/src/pages/Mainpage/components/QRCodeFetcher.jsx
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: fix

#379 [FE-#378] 관리자 페이지 하드코딩 제거
  frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
  frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
  frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx
Labels: feature

#372 [BE-#371] Penalty 부여일자를 영업일 기준으로 변경
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/type/PenaltyReasonType.java
  backend/src/main/resources/application.properties
  frontend/src/pages/Mainpage/components/Popups.jsx
Labels: feature

#381 [BE-#380] 관리자의 패널티 관리 기능 제작
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminDelPenaltyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminPenaltyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminSetPenaltyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminGetReservedResponse.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyControlResponse.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyRecordResponse.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/type/PenaltyReasonType.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/infrastructure/persistence/PenaltyRepository.java
Labels: feature

#370 [FE-#369] Toast Message의 스타일을 Status에 따라 변경되게 수정
  frontend/src/pages/Notification/NotificationMessage.jsx
Labels: feature

#382 [FE-#378] Admin 선점하기 기능 구현
  frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
  frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx
Labels: feature

#386 [FE-#384] admin 선점된 방 조회 기능 구현
  frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
Labels: feature

#388 [FE-#387] 중복 쿼리문 방지를 위한 Context Api 사용
  frontend/src/App.jsx
  frontend/src/pages/Mainpage/components/ProfileDropdown.jsx
  frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
  frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
  frontend/src/pages/Mainpage/handlers/UserContext.jsx
Labels: refactor

#390 [BE-#389] admin penalty dto 필드값 수정
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminSetPenaltyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyRecordResponse.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
Labels: fix

#385 [BE-#383] JPA Repository Refactoring
  backend/src/main/java/com/ice/studyroom/domain/admin/infrastructure/persistence/RoomTimeSlotRepository.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/infrastructure/persistence/PenaltyRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ScheduleRepository.java
Labels: refactor

#391 [BE-#] admin penalty dto 수정
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminDelPenaltyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyRecordResponse.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/RoomScheduleInfoDto.java
Labels: fix

#393 [FE-#392] 어드민의 패널티 조회,추가 그리고 해지 기능구현
  frontend/src/pages/Mainpage/Adminpage/PenaltyLogic.jsx
  frontend/src/pages/Mainpage/Adminpage/PenaltyManagement.jsx
Labels: feature

#396 [BE-#395] 관리자 room_time_slot 선점, 해지, 조회 api 제작
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminOccupyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminReleaseRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/scheduler/RoomTimeSlotScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ScheduleRepository.java
  frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx
Labels: feature

#397 [FE-#378] admin 선점 변경된 api에 적용
  frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
  frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
  frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx
Labels: feature

#399 [FE-#398] admin 선점 해지 기능 구현
  frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
Labels: feature

#401 [FE-#400] admin 선점하기 페이지 선점 가능한 방 구분
  frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
  frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx
Labels: feature, ui

#406 [BE-#405] 관리자 선점 기능 오류 해결
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/RoomScheduleInfoDto.java
  frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
  frontend/src/pages/Mainpage/Adminpage/PenaltyLogic.jsx
Labels: fix

#404 [Feature-#402, #403] 대표 예약자 반환 및 예약 취소 테스트 코드 작성
  backend/src/main/java/com/ice/studyroom/config/AppConfig.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ParticipantResponse.java
  backend/src/test/java/com/ice/studyroom/domain/admin/application/AdminServiceTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java
Labels: feature

#408 [FE-#407] 관리자 페이지 선점 완료, 해지시 ui 업데이트 및 탭 상태 저장
  frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
  frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
  frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx
Labels: feature

#411 [BE-#410] reservation 테이블 스키마에 member 외래키 추가
  README.md
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
Labels: feature

#413 [FE-#409] 예약자 및 참여자 오류 수정
  frontend/src/pages/Reservation/StudyRoomManage.jsx
Labels: fix

#416 [FE-#414] Admin 페이지 추가 기능 설정
  frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
  frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
  frontend/src/pages/Mainpage/Adminpage/PenaltyLogic.jsx
  frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx
Labels: feature

#415 [BE-#412] 예약 조회, 예약 연장 삭제 될 컬럼인(userName, userEmail) 의존성 제거
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java
Labels: refactor

#422 [FE-#420] 예약 요청 데이터 수정
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
Labels: fix

#421 [BE-#417] 개인 예약 테스트 코드 작성 및 비즈니스 로직 개선
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/Email.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ScheduleRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateReservationRequest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java
Labels: test

#424 [BE-#423] Entity 클래스 개선
  backend/src/main/java/com/ice/studyroom/domain/admin/domain/entity/RoomTimeSlot.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateScheduleRequest.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/DeleteReservationRequest.java
  backend/src/main/java/com/ice/studyroom/global/entity/BaseTimeEntity.java
  backend/src/test/java/com/ice/studyroom/domain/membership/application/MembershipServiceTest.java
  backend/src/test/java/com/ice/studyroom/domain/penalty/application/PenaltyServiceTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationExtendTest.java
  backend/src/test/java/com/ice/studyroom/helper/ReservationTestHelper.java
Labels: refactor

#426 [BE-#425] 예약 API, 패널티 API에 삭제될 컬럼에 대한 종속성 삭제 및 개선
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ReservationUpdateScheduler.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
  backend/src/test/java/com/ice/studyroom/helper/ReservationTestHelper.java
Labels: refactor

#428 [BE-#427] 지연로딩에 따른 UserRole 직렬화 실패 오류 수정
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
Labels: fix

#430 [FE-#429] 예약 조회시 데이터 저장 형식 수정
  frontend/src/pages/Reservation/StudyRoomManage.jsx
Labels: fix

#432 [BE-#431] QR code 지연 로딩 시스템 개선 및 길이 간소화
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/QRCodeService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/redis/QRCodeService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/util/QRCodeUtil.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
  backend/src/main/java/com/ice/studyroom/global/util/SecureTokenUtil.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java
Labels: refactor

#436 [BE-#434] 입실 API 요청 값을 QR 코드가 아닌 QR 토큰 전달로 수정
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/QrEntranceRequest.java
Labels: refactor

#439 [FE-#437] 메인페이지 유저 정보 업데이트
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
  frontend/src/pages/Mainpage/handlers/UserContext.jsx
Labels: fix

#440 [FE-#438] 연장 시간이 아닐 때 연장 버튼 클릭시 토스트 메세지 생성
  frontend/src/pages/Reservation/StudyRoomManage.jsx
Labels: feature

#442 [BE-#441] QR 코드 조회 기능 테스트 코드 작성
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/EncryptionService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/AESUtil.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/GetMyReservationQrCodeTest.java
Labels: test

#444 [BE-#443] 그룹 예약 테스트 코드 작성
  backend/sql/room_time_slot.sql
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateReservationRequest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/GroupReservationTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationExtendTest.java
Labels: test

#446 [BE-#445] 예약 도메인의 변수명 통일
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/util/QRCodeUtil.java
Labels: refactor
