Repository ICE-STUDYRES/ice-studyroom, pull requests merged in 2025-01, with the labels that each got.

#4 [BE -#2] 예약 생성, 취소 API 구현
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/ice/studyroom/config/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/config/SwaggerConfig.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/api/ReservationController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/dao/ReservationRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/dao/ScheduleRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ReservationStatus.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ScheduleStatus.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/dto/request/CreateReservationRequest.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/dto/request/CreateScheduleRequest.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/dto/request/DeleteReservationRequest.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/dto/response/ReservationResponse.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/dto/response/ScheduleResponse.java
  backend/src/main/java/com/ice/studyroom/domain/room/api/RoomScheduleController.java
  backend/src/main/java/com/ice/studyroom/domain/room/dao/RoomRepository.java
  backend/src/main/java/com/ice/studyroom/domain/room/dao/TimeSlotRepository.java
  backend/src/main/java/com/ice/studyroom/domain/room/domain/entity/Room.java
  backend/src/main/java/com/ice/studyroom/domain/room/domain/entity/TimeSlot.java
  backend/src/main/java/com/ice/studyroom/domain/user/domain/entity/User.java
  backend/src/main/java/com/ice/studyroom/global/entity/BaseTimeEntity.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/ice/studyroom/IceStudyRoomApplicationTests.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/api/ReservationControllerTest.java
Labels: feature

#5 [FE -#] 프론트 초기 설정
  frontend/fr-study/.gitignore
  frontend/fr-study/README.md
  frontend/fr-study/eslint.config.js
  frontend/fr-study/index.html
  frontend/fr-study/package.json
  frontend/fr-study/pnpm-lock.yaml
  frontend/fr-study/public/vite.svg
  frontend/fr-study/src/App.css
  frontend/fr-study/src/App.jsx
  frontend/fr-study/src/index.css
  frontend/fr-study/src/main.jsx
  frontend/fr-study/tailwind.config.js
  frontend/fr-study/vite.config.js
Labels: feature

#7 [FE -#] 예약 페이지 생성
  frontend/fr-study/src/pages/Reservation/BookingContext.jsx
  frontend/fr-study/src/pages/Reservation/Infoinput.css
  frontend/fr-study/src/pages/Reservation/Infoinput.jsx
  frontend/fr-study/src/pages/Reservation/RoomSelection.css
  frontend/fr-study/src/pages/Reservation/RoomSelection.jsx
  frontend/fr-study/src/pages/Reservation/TimeSelection.css
  frontend/fr-study/src/pages/Reservation/TimeSelection.jsx
Labels: feature

#9 [FE -#] 예약현황 페이지 생성
  frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.css
  frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: feature

#15 [FE -#14] 로그인, 회원가입 텍스트박스 생성
  frontend/fr-study/src/App.jsx
  frontend/fr-study/src/assets/images/hufslogo.png
  frontend/fr-study/src/pages/Mainpage/SignInPopup.jsx
  frontend/fr-study/src/pages/Mainpage/SignUpPopup.jsx
  frontend/fr-study/src/pages/Mainpage/mainpage.css
  frontend/fr-study/src/pages/Mainpage/mainpage.jsx
  frontend/fr-study/src/pages/Mainpage/popup.css
  frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: feature

#20 [BE -#18, #19]공통 응답 및 예약, 스케줄 조회 API 구현
  backend/src/main/java/com/ice/studyroom/IceStudyRoomApplication.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/api/ReservationController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/dao/ReservationRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/dao/ScheduleRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/global/dto/response/ResponseDto.java
  backend/src/main/java/com/ice/studyroom/global/exception/BusinessException.java
  backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/ice/studyroom/global/type/StatusCode.java
Labels: feature

#27 feat: UI 통합
  frontend/fr-study/src/pages/Mainpage/mainpage.css
  frontend/fr-study/src/pages/Mainpage/mainpage.jsx
  frontend/fr-study/src/pages/Mainpage/popup.css
  frontend/fr-study/src/pages/Reservation/StudyRoomBooking.jsx
  frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.css
  frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: feature

#33 [BE -#28] 회원 도메인 설정
  backend/build.gradle
  backend/src/main/java/com/ice/studyroom/config/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/Email.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
  backend/src/main/java/com/ice/studyroom/domain/user/domain/entity/User.java
  backend/src/main/resources/application.properties
Labels: feature

#34 [BE -#29] 회원가입 구현 및 인증 인가 설정
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/JwtToken.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtAuthenticationFilter.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberCreateResponse.java
Labels: feature

#35 [BE -#32] 로그인 구현 및 인증 인가를 위한 토큰 반환
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/SecurityUser.java
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/CustomUserDetailsService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberLoginRequest.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLoginResponse.java
Labels: feature

#50 [BE -#49] Redis 환경설정 및 연결
  backend/build.gradle
  backend/src/main/java/com/ice/studyroom/config/RedisConfig.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/ice/studyroom/config/RedisConnectionTest.java
Labels: chore

#51 [BE -#46] 토큰 재발급 구현
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/TokenService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/exception/InvalidRefreshTokenException.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/TokenRequest.java
Labels: feature

#52 [BE -#47] 로그아웃 구현
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberCreateResponse.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberResponse.java
Labels: feature

#57 [hotfix] 엔티티 매핑 버그 수정
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
Labels: fix

#61 [BE -#60] Access 토큰 헤더로 변경
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/TokenRequest.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLoginResponse.java
Labels: refactor

#62 [FE -#39] 로그인, 회원가입 API 연결
  frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
  frontend/fr-study/vite.config.js
Labels: fix

#64 [BE -#63] 내 예약 확인하기 및 전체 스케주 조회 구현
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/TokenService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ScheduleRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateReservationRequest.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateScheduleRequest.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/DeleteReservationRequest.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ReservationResponse.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ScheduleResponse.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/presentation/ReservationControllerTest.java
Labels: feature

#59 [BE -#54] 예약 알림 메일 전송 의존성 추가, SMTP 설정 및 구현
  backend/build.gradle
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/global/controller/EmailController.java
  backend/src/main/java/com/ice/studyroom/global/service/EmailService.java
  backend/src/main/resources/application.properties
Labels: feature

#67 [BE -#12] Admin 도메인 특정 시간 예약 기능 구현
  backend/sql/room_time_slot.sql
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminCreateReserveRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminCreateReserveResponse.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/entity/RoomTimeSlot.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/type/DayOfWeekStatus.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/type/RoomTimeSlotStatus.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/type/RoomType.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/infrastructure/persistence/RoomTimeSlotRepository.java
Labels: feature

#68 [BE] 최소인원 컬럼 추가 및 사용자 이름 모킹
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateReservationRequest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/presentation/ReservationControllerTest.java
Labels: fix

#70 [FE -#69] 메인페이지 ui, 핸들러 컴포넌트 분리
  frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
  frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx
Labels: refactor

#73 [hotfix] RoomTimeSlot STATUS , 관리자선점 용어변경
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminCreateOccupyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminCreateOccupyResponse.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminCreateReserveResponse.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/entity/RoomTimeSlot.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/type/DayOfWeekStatus.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/type/RoomTimeSlotStatus.java
Labels: refactor, chore

#77 [FE-#74] 이메일 인증, 확인 텍스트박스 및 버튼 생성
  frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
  frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx
Labels: feature

#78 [FE -#66] 예약 확인 기능 구현
  frontend/fr-study/src/App.jsx
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
  frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: feature

#79 [BE -#71, 72] 이메일 인증 코드 발송 및 확인 로직 구현
  backend/gradlew
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/TokenService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/email/EmailVerificationService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/EmailVerificationRequest.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberEmailVerificationRequest.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberEmailResponse.java
  backend/src/main/java/com/ice/studyroom/global/service/CacheService.java
  backend/src/main/java/com/ice/studyroom/global/service/RedisService.java
  backend/src/main/java/com/ice/studyroom/global/type/StatusCode.java
  backend/src/test/java/com/ice/studyroom/domain/membership/infrastructure/email/EmailVerificationServiceTest.java
Labels: feature

#81 [BE -#80] 스케줄 자동 생성 스케줄러 구현
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTask.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTaskTest.java
Labels: feature

#82 [BE -#76] 회원가입 요청 dto 업데이트
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/VerificationCodeCacheService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/email/EmailVerificationService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
  backend/src/test/java/com/ice/studyroom/domain/membership/infrastructure/email/EmailVerificationServiceTest.java
Labels: feature

#91 [BE-#30, #90] 비밀번호 수정 구현 및 AccessToken 만료 확인
  backend/src/main/java/com/ice/studyroom/domain/identity/exception/InvalidJwtException.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtAuthenticationFilter.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/TokenRequest.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/UpdatePasswordRequest.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/entity/RoomTimeSlot.java
Labels: feature

#87 [BE-#86] 관리자 선점 목록 조회 및 선점 해지 기능
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminCreateOccupyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminDeleteOccupyResponse.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/entity/RoomTimeSlot.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/infrastructure/persistence/RoomTimeSlotRepository.java
Labels: feature

#92 [BE-#58] QR 생성 및 조회 구현
  backend/build.gradle
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/EncryptionService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/QRCodeService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/AESUtil.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/QRCodeUtil.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
  backend/src/main/java/com/ice/studyroom/domain/room/api/RoomScheduleController.java
  backend/src/main/java/com/ice/studyroom/domain/room/dao/RoomRepository.java
  backend/src/main/java/com/ice/studyroom/domain/room/dao/TimeSlotRepository.java
  backend/src/main/java/com/ice/studyroom/domain/room/domain/entity/Room.java
  backend/src/main/java/com/ice/studyroom/domain/room/domain/entity/TimeSlot.java
  backend/src/main/resources/application.properties
Labels: feature

#95 [BE - #88, #89, #93, #94] Member Penalty 적용 및 비즈니스 처리
  backend/build.gradle
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Penalty.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/Email.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/PenaltyRepository.java
  backend/src/main/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateScheduler.java
  backend/src/test/java/com/ice/studyroom/domain/membership/application/MembershipServiceTest.java
  backend/src/test/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateSchedulerTest.java
Labels: feature

#98 [FE -#97] 전체 예약 조회 페이지 수정
  frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: feature

#101 [BE - #100, #102] Swagger 오류 해결 및 문서 업데이트
  backend/build.gradle
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
  backend/src/main/java/com/ice/studyroom/global/controller/EmailController.java
Labels: chore

#103 [BE - #99] Admin penalty 증가/차감/목록 조회 기능 추가
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/domain/entity/RoomTimeSlot.java
  backend/src/main/java/com/ice/studyroom/domain/admin/domain/type/DayOfWeekStatus.java
  backend/src/main/java/com/ice/studyroom/domain/admin/domain/type/RoomTimeSlotStatus.java
  backend/src/main/java/com/ice/studyroom/domain/admin/domain/type/RoomType.java
  backend/src/main/java/com/ice/studyroom/domain/admin/infrastructure/persistence/RoomTimeSlotRepository.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminPenaltyRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyControlResponse.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyRecordResponse.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/PenaltyRepository.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/type/RoomType.java
  backend/src/main/java/com/ice/studyroom/domain/room_timeslot/infrastructure/persistence/RoomTimeSlotRepository.java
  backend/src/test/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateSchedulerTest.java
Labels: feature

#108 [BE-#107] 최근 예약 조회하기
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetMostRecentReservationResponse.java
Labels: feature

#112 [BE-#111] RT 반환 오류 수정 및 예약 DDL 추가
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtAuthenticationFilter.java
  backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
Labels: feature, fix

#113 [BE - #106] member, penalty table 변경에 따른 코드 수정
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyRecordResponse.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Penalty.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/type/PenaltyReasonType.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/type/PenaltyStatus.java
  backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/PenaltyRepository.java
  backend/src/main/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateScheduler.java
  backend/src/test/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateSchedulerTest.java
Labels: chore

#118 [FE - #115] RTR 토큰 관리 기법 적용
  frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
  frontend/fr-study/src/pages/Reservation/StudyRoomBookingUI.jsx
  frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: feature, fix
