Repository ICE-STUDYRES/ice-studyroom, pull requests merged in 2025-04, with the labels that each got.

#453 [BE-#452] QR 입실 테스트 코드 작성
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/QrEntranceResponse.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrEntranceTest.java
Labels: test

#456 [BE-#455] 최근 예약 기록 확인 API 응답에 시작시간, 종료시간 추가
  backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetMostRecentReservationResponse.java
Labels: refactor

#458 [FE-#457] 시작, 종료 시간 데이터 추가
  frontend/src/pages/Mainpage/Mainpage.jsx
Labels: refactor

#460 [FE-#459] QR코드 수정
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
Labels: feature

#463 [FE-#462] 다른 페이지에서 로그인 시도 시 에러 문구 생성
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: fix

#465 [FE-#464] 비로그인 상태에서 페이지 강제 접근시 메인페이지로 이동
  frontend/src/pages/Reservation/StudyRoomManage.jsx
  frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
  frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: feature

#467 [BE-#466] member entity의 penalty가 업데이트되지 않는 문제 해결
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/test/java/com/ice/studyroom/domain/membership/application/MembershipServiceTest.java
Labels: bug, feature

#469 [BE-#468] JWT 필터 예외 처리 핸들러 등록 및 로깅 설정
  backend/src/main/java/com/ice/studyroom/config/SecurityConfig.java
  backend/src/main/java/com/ice/studyroom/config/WebConfig.java
  backend/src/main/java/com/ice/studyroom/domain/identity/exception/InvalidJwtException.java
  backend/src/main/java/com/ice/studyroom/domain/identity/exception/InvalidRefreshTokenException.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
  backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLoginResponse.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/interceptor/PenaltyCheckInterceptor.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTask.java
  backend/src/main/java/com/ice/studyroom/global/exception/jwt/JwtAuthenticationException.java
  backend/src/main/java/com/ice/studyroom/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/ice/studyroom/global/security/handler/JwtAccessDeniedHandler.java
  backend/src/main/java/com/ice/studyroom/global/security/handler/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/ice/studyroom/global/security/jwt/JwtToken.java
  backend/src/main/java/com/ice/studyroom/global/security/jwt/JwtTokenProvider.java
  backend/src/main/java/com/ice/studyroom/global/security/service/TokenService.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/GetMyReservationQrCodeTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/GroupReservationTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrEntranceTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationExtendTest.java
Labels: refactor

#472 [BE-#471] Penalty 서비스 계층 리팩토링
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/service/PenaltyDomainService.java
  backend/src/test/java/com/ice/studyroom/domain/penalty/application/PenaltyServiceTest.java
  backend/src/test/java/com/ice/studyroom/domain/penalty/domain/service/PenaltyDomainServiceTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTaskTest.java
Labels: refactor

#475 [Feature-#474] 핵심 비즈니스 로직에 의미 있는 로그 메시지 추가
  backend/Dockerfile
  backend/build.gradle
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/application/EmailVerificationService.java
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/CustomUserDetailsService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/service/PenaltyDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/interceptor/PenaltyCheckInterceptor.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/redis/QRCodeService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTask.java
  backend/src/main/java/com/ice/studyroom/global/filter/LoggingMdcFilter.java
  backend/src/main/java/com/ice/studyroom/global/security/service/TokenService.java
  backend/src/main/java/com/ice/studyroom/global/service/GmailService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/logback-spring.xml
Labels: feature

#477 [BE-#476] 로그 파일 영속성 설정
  .github/workflows/deploy-server.yml
Labels: chore

#479 [BE-#478] 서비스 로깅 메시지 통일 및 유틸리티 적용
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/domain/util/AdminLogUtil.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/util/MembershipLogUtil.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/service/PenaltyDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/penalty/domain/util/PenaltyLogUtil.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/util/ReservationLogUtil.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/GroupReservationTest.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
Labels: refactor

#481 [BE-#480] Actuator + Micrometer + Prometheus 연동
  backend/build.gradle
  backend/src/main/java/com/ice/studyroom/config/SecurityConfig.java
  backend/src/main/resources/application.properties
Labels: chore

#483 [BE-#482] Prometheus 연동을 위한 메트릭 태그 및 JVM 모니터링 속성 추가
  backend/src/main/resources/application.properties
Labels: chore

#485 [BE-#484] Membership 도메인의 이메일, 비밀번호 비즈니스 로직 분리 및 VO를 활용한 자기 유효성 검사 구현
  backend/src/main/java/com/ice/studyroom/IceStudyRoomApplication.java
  backend/src/main/java/com/ice/studyroom/domain/identity/domain/SecurityUser.java
  backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/encrypt/PasswordEncryptor.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/encrypt/PasswordEncryptorImpl.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/manage/MemberEmailService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/manage/MemberPasswordService.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/Email.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/EncodedPassword.java
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/RawPassword.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  backend/src/test/java/com/ice/studyroom/domain/reservation/application/GroupReservationTest.java
Labels: refactor
