Repository ICE-STUDYRES/ice-studyroom, pull requests merged in 2025-05, with the labels that each got.

#487 [BE-#486] 이메일 예약 이용 시간 버그 수정
  backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
  backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
  frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
Labels: bug

#491 [BE-#490] 관리자의 방 정보 조회 및 방 타입 변경 기능 구현
  backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/domain/service/manage/RoomModificationService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/domain/service/policy/RoomPolicyService.java
  backend/src/main/java/com/ice/studyroom/domain/admin/infrastructure/persistence/RoomTimeSlotRepository.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminModRoomTypeRequest.java
  backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/RoomInfoResponse.java
  backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/ice/studyroom/global/exception/RoomNotFoundException.java
Labels: feature

#493 [FE-#488] 회원가입 페이지 Usability 향상
  frontend/src/pages/Mainpage/Mainpage.jsx
  frontend/src/pages/Mainpage/components/Signup.jsx
Labels: feature

#494 [FE-#489] 예약 현황 페이지 같은 예약 병합처리
  frontend/src/pages/ReservationStatus/ReservationStatus.jsx
Labels: fix
